name: Deploy to EC2 on develop push

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 프로젝트 폴더로 이동
            cd /home/ubuntu/customer-chefriend-frontend # 실제 EC2의 프로젝트 경로로 수정
            # develop 브랜치로 이동
            git fetch origin
            git checkout -B develop origin/develop
            # 의존성 설치 (package-lock.json 기준)
            npm ci
            # 빌드
            npm run build
            # PM2로 앱 시작
            if pm2 list | grep -q "chefriend-customer"; then
              pm2 delete chefriend-customer
            fi
            pm2 start npm --name chefriend-customer -- run start -- -p 3005
            # PM2 상태 저장 (서버 재부팅 시 자동 실행)
            pm2 save
            # nginx 재시작
            sudo systemctl restart nginx